"""Structured field classification per tab: must / important / optional.

This is a code config — NOT a prompt. It drives validation logic and
data quality checks. Fields classified as:
- must: required to create a valid record (block if missing)
- important: significantly improves record quality (flag but don't block)
- important_conditional: important only in certain contexts
- optional: nice to have, never flagged

Note: site_id and ticket_id are auto-generated by the bot — never ask
the user for these directly (use friendly prompts like "Hangi saha için?").
"""

from __future__ import annotations

from typing import Any

FIELD_REQUIREMENTS: dict[str, dict[str, Any]] = {
    "sites": {
        "must": [
            "customer", "city", "country", "facility_type",
            "contract_status", "supervisor_1", "phone_1",
        ],
        "important": [
            "go_live_date", "address", "dashboard_link", "whatsapp_group",
        ],
        "optional": [
            "email_1", "supervisor_2", "phone_2", "email_2", "notes",
        ],
    },
    "hardware_inventory": {
        "must": ["site_id", "device_type", "qty"],
        "important_conditional": {
            "hw_version": {
                "except_device_types": [
                    "Charging Dock", "Power Bank", "Power Adapter",
                    "USB Cable", "Other",
                ],
            },
            "fw_version": {
                "except_device_types": [
                    "Charging Dock", "Power Bank", "Power Adapter",
                    "USB Cable", "Other",
                ],
            },
        },
        "optional": ["last_verified", "notes"],
    },
    "implementation_details": {
        "must": ["internet_provider", "ssid"],
        "important": [
            "password", "gateway_placement", "charging_dock_placement",
            "dispenser_anchor_placement", "handwash_time", "tag_buzzer_vibration",
            "entry_time", "dispenser_anchor_power_type",
        ],
        "must_when_facility_type": {
            "Food": [
                "clean_hygiene_time", "hp_alert_time", "hand_hygiene_time",
                "hand_hygiene_interval", "hand_hygiene_type",
            ],
            "Healthcare": [
                "tag_clean_to_red_timeout",
            ],
        },
        "optional": ["other_details"],
    },
    "support_log": {
        "must": [
            "site_id", "received_date", "type", "status",
            "issue_summary", "responsible",
        ],
        "important_conditional": {
            "root_cause": {"required_when_status_not": ["Open"]},
            "resolution": {"required_when_status": ["Resolved"]},
            "resolved_date": {"required_when_status": ["Resolved"]},
            "devices_affected": "always_important",
        },
        "optional": ["notes"],
    },
    "stock": {
        "must": ["location", "device_type", "qty", "condition"],
        "important": ["hw_version", "fw_version"],
        "optional": ["reserved_for", "notes"],
    },
}

CONTEXT_RULES: dict[str, dict[str, Any]] = {
    "awaiting_installation": {
        "skip_tabs": [
            "implementation_details", "hardware_inventory", "support_log",
        ],
    },
}
